### ISSUE TITLE
Generic Error Not working in branch 2.2

### ISSUE THREAD

**Issue by BGuimberteau** [spree-contrib/better_spree_paypal_express#112]
When i configure with my API Credentials, i got this error : Generic Error

backtrace if that's can help you :

    Processing by Spree::PaypalController#express as HTML
      Parameters: {"authenticity_token"=>"RvMA3waHKe3f5BH0Xh7OMFe87dvsXlxJcLgE1vzenF4=", "payment_method_id"=>"5", "locale"=>"fr"}
      Spree::User Load (0.3ms)  SELECT "spree_users".* FROM "spree_users" WHERE "spree_users"."id" = 1 ORDER BY "spree_users"."id" ASC LIMIT 1
      Spree::Order Load (0.2ms)  SELECT "spree_orders".* FROM "spree_orders" WHERE "spree_orders"."user_id" = ? AND "spree_orders"."completed_at" IS NULL AND "spree_orders"."created_by_id" = 1 ORDER BY created_at DESC LIMIT 1  [["user_id", 1]]
      Spree::Order Load (0.2ms)  SELECT "spree_orders".* FROM "spree_orders" WHERE "spree_orders"."id" = 26 AND "spree_orders"."currency" = 'EUR' LIMIT 1
      Spree::Adjustment Load (0.2ms)  SELECT "spree_adjustments".* FROM "spree_adjustments" WHERE "spree_adjustments"."adjustable_type" = 'Spree::Order' AND "spree_adjustments"."adjustable_id" IN (26) ORDER BY spree_adjustments.created_at ASC
      Spree::LineItem Load (0.2ms)  SELECT "spree_line_items".* FROM "spree_line_items" WHERE "spree_line_items"."order_id" = ? ORDER BY created_at ASC  [["order_id", 26]]
      Spree::Variant Load (0.1ms)  SELECT "spree_variants".* FROM "spree_variants" WHERE "spree_variants"."id" = ? LIMIT 1  [["id", 1]]
      Spree::Product Load (0.1ms)  SELECT "spree_products".* FROM "spree_products" WHERE "spree_products"."id" = ? LIMIT 1  [["id", 1]]
      Spree::Product::Translation Load (0.1ms)  SELECT "spree_product_translations".* FROM "spree_product_translations" WHERE "spree_product_translations"."spree_product_id" = ?  [["spree_product_id", 1]]
      Spree::Adjustment Load (0.2ms)  SELECT "spree_adjustments".* FROM "spree_adjustments" WHERE (order_id = 26 OR (adjustable_id = 26 AND adjustable_type = 'Spree::Order')) AND "spree_adjustments"."eligible" = 't'
      Spree::Adjustment Load (0.1ms)  SELECT "spree_adjustments".* FROM "spree_adjustments" WHERE (order_id = 26 OR (adjustable_id = 26 AND adjustable_type = 'Spree::Order')) AND "spree_adjustments"."source_type" = 'Spree::TaxRate' AND "spree_adjustments"."included" = 'f'
      Spree::Adjustment Load (0.1ms)  SELECT "spree_adjustments".* FROM "spree_adjustments" WHERE (order_id = 26 OR (adjustable_id = 26 AND adjustable_type = 'Spree::Order')) AND "spree_adjustments"."adjustable_type" = 'Spree::Shipment'
      Spree::PaymentMethod Load (0.1ms)  SELECT "spree_payment_methods".* FROM "spree_payment_methods" WHERE "spree_payment_methods"."deleted_at" IS NULL AND "spree_payment_methods"."id" = ? LIMIT 1  [["id", "5"]]
      CACHE (0.0ms)  SELECT "spree_payment_methods".* FROM "spree_payment_methods" WHERE "spree_payment_methods"."deleted_at" IS NULL AND "spree_payment_methods"."id" = ? LIMIT 1  [["id", "5"]]
      CACHE (0.0ms)  SELECT "spree_payment_methods".* FROM "spree_payment_methods" WHERE "spree_payment_methods"."deleted_at" IS NULL AND "spree_payment_methods"."id" = ? LIMIT 1  [["id", "5"]]
      CACHE (0.0ms)  SELECT "spree_payment_methods".* FROM "spree_payment_methods" WHERE "spree_payment_methods"."deleted_at" IS NULL AND "spree_payment_methods"."id" = ? LIMIT 1  [["id", "5"]]
      CACHE (0.0ms)  SELECT "spree_payment_methods".* FROM "spree_payment_methods" WHERE "spree_payment_methods"."deleted_at" IS NULL AND "spree_payment_methods"."id" = ? LIMIT 1  [["id", "5"]]
      CACHE (0.0ms)  SELECT "spree_payment_methods".* FROM "spree_payment_methods" WHERE "spree_payment_methods"."deleted_at" IS NULL AND "spree_payment_methods"."id" = ? LIMIT 1  [["id", "5"]]
      CACHE (0.0ms)  SELECT "spree_payment_methods".* FROM "spree_payment_methods" WHERE "spree_payment_methods"."deleted_at" IS NULL AND "spree_payment_methods"."id" = ? LIMIT 1  [["id", "5"]]
      Spree::Shipment Load (0.1ms)  SELECT "spree_shipments".* FROM "spree_shipments" WHERE "spree_shipments"."order_id" = ?  [["order_id", 26]]
      CACHE (0.0ms)  SELECT "spree_payment_methods".* FROM "spree_payment_methods" WHERE "spree_payment_methods"."deleted_at" IS NULL AND "spree_payment_methods"."id" = ? LIMIT 1  [["id", "5"]]
      Spree::Address Load (0.1ms)  SELECT "spree_addresses".* FROM "spree_addresses" WHERE "spree_addresses"."id" = ? LIMIT 1  [["id", 47]]
      Spree::Country Load (0.1ms)  SELECT "spree_countries".* FROM "spree_countries" WHERE "spree_countries"."id" = ? LIMIT 1  [["id", 29]]
      CACHE (0.0ms)  SELECT "spree_payment_methods".* FROM "spree_payment_methods" WHERE "spree_payment_methods"."deleted_at" IS NULL AND "spree_payment_methods"."id" = ? LIMIT 1  [["id", "5"]]
    I, [2014-07-17T17:14:09.151405 #2234]  INFO -- : Action: SetExpressCheckout
    I, [2014-07-17T17:14:09.151469 #2234]  INFO -- : Request[post]: https://api-3t.sandbox.paypal.com/2.0/
    I, [2014-07-17T17:14:10.848464 #2234]  INFO -- : Response[200]: OK, Duration: 1.697s
    Redirected to http://yvc.dev:3000/fr/checkout/payment
    Completed 302 Found in 1746ms (ActiveRecord: 2.2ms)

    Started GET "/fr/checkout/payment" for 127.0.0.1 at 2014-07-17 17:14:10 +0200
    Processing by Spree::CheckoutController#edit as HTML

Thanks in advance for you help.

**Comment by poguez** [comment]
@Allanon29 could you solve it?

**Comment by Allanon29** [comment]
@poguez unfortunately not yet.

**Comment by alepore** [comment]
if it was VAT related should be fixed on all branches (better late than never)
