### ISSUE TITLE
API endpoints

### ISSUE THREAD

**Issue by radar** [spree-contrib/better_spree_paypal_express#13]
If a user selects the PayPal Express payment method, there is currently no way for them to proceed through the checkout process if they're doing it through Spree's API component. (see [this thread](https://groups.google.com/forum/#!topic/spree-user/nXYWZW8PQls) for an example of that)

Therefore I propose that we add an API controller to this extension which serves up two endpoints:

* `/orders/:number/paypal/start` - Same as `Spree::PaypalController#express`
* `/orders/:number/paypal/confirm` - Same as `Spree::PaypalController#confirm`

With the code for the API + frontend controllers being identical, I think we should move that logic out of the controllers and into a service object of sorts.

**Comment by MisinformedDNA** [comment]
@radar, are you saying that for the simplest solution, we can just copy the backend controller to the API controller and copy the routes and then that's it?

**Comment by radar** [comment]
I no longer work on Spree and so I am unable to advise here.

**Comment by williscool** [comment]
Looks like Im going to have to build this. Working on an ember app that communicates with spree via the api

**Comment by jspizziri** [comment]
@williscool, I think the top priority for now should be to get the builds passing again. After that, I think it will be more appropriate to propose and undertake enhancements such as this.

Any help you could do to speed the process of betting the build passing would be much appreciated. Other than that, I encourage you to fork the repo and build this feature out. At that point you can submit a PR to be reviewed (however, it probably won't be merged until the build is passing) if the community likes it then we'll get it merged in.

**Comment by williscool** [comment]
:( when was the last time the build passed?

**Comment by jspizziri** [comment]
I'm not sure, I only recently got involved. we're actively working and discussing it if you'd like to chime in.

https://github.com/spree-contrib/better_spree_paypal_express/issues/165

**Comment by MisinformedDNA** [comment]
This issue should be reopened so we know that it still needs to be done.

**Comment by williscool** [comment]
working on a pull request for this. should be ready soon. quite rough around the edges though

**Comment by williscool** [comment]
boom
