### ISSUE TITLE
Is there baked in support for Paypal Mobile Express?

### ISSUE THREAD

**Issue by kylemacey** [spree-contrib/better_spree_paypal_express#133]
We've been having issues with our mobile customers checking out with Paypal Express. According to [the documentation on Paypal's website](https://developer.paypal.com/docs/classic/products/mobile-express-checkout/), additional parameters are required to support mobile payments.

Is there support for this in this extension? If not, does anyone want to go in with me on a PR for this feature?

**Comment by tomashn** [comment]
Hi, is it different spree extension or you made your modifications? Can you share where have you found the integration?
