### ISSUE TITLE
Spree 2-3-stable - Generic error when clicking on the PP button

### ISSUE THREAD

**Issue by Allanon29** [spree-contrib/better_spree_paypal_express#141]
As stated in the subject, I get a generic error (flash message) when I click on the payment button.
I use Spree 2-3-stable.
Rails 4.1.8
My PayPal password, username, etc are surely correctly set in admin. 
Solution is set to Mark.
Server is set to live.
Test mode is off.
Environment is set to production.
Tried with auto capture on and off but the same thing happens.

**Comment by poguez** [comment]
same here

**Comment by Allanon29** [comment]
Now it works in development mode, but still the same error in production.

**Comment by alepore** [comment]
if it was VAT related should be fixed on all branches (better late than never)
