### ISSUE TITLE
Upgrading to Spree 3-0-stable breaks Extension

### ISSUE THREAD

**Issue by bmurtagh** [spree-contrib/better_spree_paypal_express#149]
Tonight I upgraded from Rails 4.1.8 to Rails 4.2 and Spree 2-4-stable to 3-0-stable. I checked this repo for a 3-0-stable branch, but one didn't exist so I went with master & a prayer. After the 3-0-stable upgrade, the Store failed to load on Heroku. 

The Heroku logs are Gisted here: https://gist.github.com/bmurtagh/78c97889e0337dc1da0d#file-gistfile1-txt

To get to the point, the error is:

/app/vendor/bundle/ruby/2.1.0/bundler/gems/better_spree_paypal_express-dcdd963524ef/app/controllers/spree/paypal_controller.rb:3:in `<class:PaypalController>': undefined local variable or method `ssl_allowed' for Spree::PaypalController:Class (NameError)

ssl_allowed appears to have been introduced back on June 30, 2014 in the commit: https://github.com/spree-contrib/better_spree_paypal_express/commit/ad3c01166ac9a723f8b70d79d997de9570b78a0b#diff-2f8ef701be3247d5c1ddac958eb3320b

**Comment by futhr** [comment]
It was removed from Spree Dec 25, 2014, see: https://github.com/spree/spree/pull/5827.

**Comment by romul** [comment]
Fixed https://github.com/spree-contrib/better_spree_paypal_express/commit/6bf2f7eca22c6b791b1f6e74d61769b6ec9b3dfb
