### ISSUE TITLE
During paypal checkout, get error, "Could not find table 'spree_paypal_express_checkouts'"

### ISSUE THREAD

**Issue by sybind** [spree-contrib/better_spree_paypal_express#158]
I'm getting a missing table error after I click the pay now button. I'm using the sandbox credentials and the 2-4-stable branch.

I, [2015-03-14T21:18:46.707357 #11922]  INFO -- : Redirected to https://www.sandbox.paypal.com/webscr?cmd=_express-checkout&token=EC-9N945501F3397335J&useraction=commit
I, [2015-03-14T21:18:46.707794 #11922]  INFO -- : Completed 302 Found in 2131ms (ActiveRecord: 4.2ms)
I, [2015-03-14T21:19:14.774863 #11922]  INFO -- : Started GET "/paypal/confirm?payment_method_id=3&utm_nooverride=1&token=EC-9N945501F3397335J&PayerID=UDVW9RJAAV8GA" for 10.8.0.2 at 2015-03-14 21:19:14 +0000
I, [2015-03-14T21:19:14.777158 #11922]  INFO -- : Processing by Spree::PaypalController#confirm as HTML
I, [2015-03-14T21:19:14.777241 #11922]  INFO -- :   Parameters: {"payment_method_id"=>"3", "utm_nooverride"=>"1", "token"=>"EC-9N945501F3397335J", "PayerID"=>"UDVW9RJAAV8GA"}
D, [2015-03-14T21:19:14.780879 #11922] DEBUG -- :   ESC[1mESC[35mSpree::Preference Load (0.3ms)ESC[0m  SELECT  "spree_preferences".* FROM "spree_preferences"  WHERE "spree_preferences"."key" = 'spree/frontend_configuration/locale' LIMIT 
1
D, [2015-03-14T21:19:14.784412 #11922] DEBUG -- :   ESC[1mESC[36mSpree::User Load (0.8ms)ESC[0m  ESC[1mSELECT  "spree_users".* FROM "spree_users"  WHERE "spree_users"."deleted_at" IS NULL AND "spree_users"."id" = 1  ORDER BY "spree_users
"."id" ASC LIMIT 1ESC[0m
D, [2015-03-14T21:19:14.787155 #11922] DEBUG -- :   ESC[1mESC[35mSpree::Store Load (0.3ms)ESC[0m  SELECT  "spree_stores".* FROM "spree_stores"  WHERE (url like '%10.8.0.1%')  ORDER BY "spree_stores"."id" ASC LIMIT 1
D, [2015-03-14T21:19:14.788731 #11922] DEBUG -- :   ESC[1mESC[36mSpree::Store Load (0.3ms)ESC[0m  ESC[1mSELECT  "spree_stores".* FROM "spree_stores"  WHERE "spree_stores"."default" = 't'  ORDER BY "spree_stores"."id" ASC LIMIT 1ESC[0m
D, [2015-03-14T21:19:14.790666 #11922] DEBUG -- :   ESC[1mESC[35mSpree::Order Load (0.7ms)ESC[0m  SELECT  "spree_orders".* FROM "spree_orders"  WHERE "spree_orders"."completed_at" IS NULL AND "spree_orders"."currency" = 'USD' AND "spree_
orders"."guest_token" = 'b-gY3cKOMzSPm3d0A3HfZw' AND "spree_orders"."store_id" = 1 AND "spree_orders"."user_id" = 1 LIMIT 1
D, [2015-03-14T21:19:14.793080 #11922] DEBUG -- :   ESC[1mESC[36mSpree::Adjustment Load (0.3ms)ESC[0m  ESC[1mSELECT "spree_adjustments".* FROM "spree_adjustments"  WHERE "spree_adjustments"."adjustable_type" = 'Spree::Order' AND "spree_a
djustments"."adjustable_id" IN (2)  ORDER BY spree_adjustments.created_at ASCESC[0m
D, [2015-03-14T21:19:14.796030 #11922] DEBUG -- :   ESC[1mESC[35mSpree::Order Load (0.2ms)ESC[0m  SELECT "spree_orders".* FROM "spree_orders"  WHERE "spree_orders"."user_id" = ? AND "spree_orders"."completed_at" IS NULL AND (id != 2)  [[
"user_id", 1]]
I, [2015-03-14T21:19:14.798510 #11922]  INFO -- : Completed 500 Internal Server Error in 21ms
F, [2015-03-14T21:19:14.804432 #11922] FATAL -- : 
ActiveRecord::StatementInvalid (Could not find table 'spree_paypal_express_checkouts'):

**Comment by alepore** [comment]
did you run the installer? `bundle exec rails g spree_paypal_express:install`
