### ISSUE TITLE
CI Builds Failing

### ISSUE THREAD

**Issue by diabolo** [spree-contrib/better_spree_paypal_express#165]
All the active branch and default branch builds are failing.

Is this gem supported and fit for purpose? Would it be safer to use spree_paypal_express?

TIA

Andrew

**Comment by jspizziri** [comment]
The builds are currently failing and there is currently an initiative to clean them up, of which I'm a part.

I just recently got involved with this initiative because I'm using the `master` branch in a project. It's working well in that project despite the fact that the builds are failing.

Any help in this regard would be welcomed and appreciated!

**Comment by alepore** [comment]
the main problem are integration tests that click all over the paypal interface to simulate a real order.
paypal sandbox is not reliable, sometimes you get an interface, sometimes a different one (new??), sometimes a timeout.
what about just stubbing a paypal result and remove those tests?

**Comment by alepore** [comment]
what we should test is to pass correct values to paypal, and to complete the order when a proper response is received.
what happens in the middle is a paypal problem, imho.

**Comment by jspizziri** [comment]
The only problem I see with that is that, hypothetically, the PayPal API could change without notice. If a proper response was never received, then what would happen?

**Comment by alepore** [comment]
if PayPal API breaks... all stores breaks, even old ones.
That should not happen, and i think it's not our job to test that.

Now some fun: here are screenshots from two consecutive runs, same test.
Note the completely different interfaces (and both are stuck on some js waiting).


![screen shot 2015-04-29 at 09 12 51](https://cloud.githubusercontent.com/assets/557414/7386104/429a5c60-ee50-11e4-8530-1abf70cd6e6a.png)

and

![screen shot 2015-04-29 at 09 12 33](https://cloud.githubusercontent.com/assets/557414/7386105/429d2e72-ee50-11e4-9a81-9f4dc8589413.png)

there's some work and ugly workarounds here: https://github.com/alepore/better_spree_paypal_express 
it's not complete but sincerely i'm tired to spend hours on matching elements on random paypal interfaces (i think i saw a third one...)

**Comment by alepore** [comment]
failing integration test are skipped at the moment
