### ISSUE TITLE
Paypal ClientID and Secret mapping to 'password' and 'signature'?

### ISSUE THREAD

**Issue by midwire** [spree-contrib/better_spree_paypal_express#166]
I hesitate to ask this but I cannot find an answer in all of my searching.

On the README we see the following instruction:

> Enter the email address, password and signature from the "API Credentials" tab for the Business account on PayPal.

However, on the Paypal account configuration page we see:

* Sandbox Account
* Sandbox Endpoint
* Client ID
* Secret

I've tried various mappings between 'password' and 'signature' in Spree, and 'Client ID' and 'Secret' but I keep getting:

> PayPal failed. Security header is not valid

Not sure if I should use the actual Paypal login account password, or 'Client ID' or 'Signature'. I feel stupid. Clearly everyone but me seems to have figured this out. I apologize for my ignorance but any help will be appreciated.

**Comment by vmueller71** [comment]
Did you find a solution for this? 
Seems you are not the only feeling stupid as I can't figure it out as well ;)
Tried it with various combinations but always get the same response from PayPal ("Security header is not valid)

Any help would be greatly appreciated.

**Comment by midwire** [comment]
I have not. It seems the project has been all but abandoned. I've not worked in this issue since May 8, 2015, but when/if I get back to it and find a solution, I will post it here. Sorry.

**Comment by jspizziri** [comment]
The project hasn't been abandoned, rather we're trying to revitalize it by getting the builds passing and encouraging more contribution. We highly appreciate any contributions from the community that uses the software and would welcome one of you to dig into the code and submit a PR for this issue if  you find one, or proper documentation if that is needed.

**Comment by alepore** [comment]
@midwire you're probably on the wrong paypal section, you need **API** username, password and key, not the Paypal account login credentials

**Comment by alepore** [comment]
on the sandbox it's super clear, on the real accounts the interface is different but they are still named API username, API password etc.
![screen shot 2015-06-25 at 17 40 49](https://cloud.githubusercontent.com/assets/557414/8358607/71175eec-1b61-11e5-8765-3bf7b523344b.png)

**Comment by nuno84** [comment]
I was facing this issue.
You must use the sandbox account for your testing  purposes. My guess is that as I did, you were using the production paypal account.
The image that alepore shown is the correct one. Look for a dialog like that one.

**Comment by midwire** [comment]
Thanks for all the help. I finally found the correct place to get the signature. Everything works great now! Kudos!

**Comment by jcgdjob** [comment]
The UX design of Paypal always bad.
Here's the steps:
1) Login to developer.paypal.com
2) on Menu: Sandbox -> Accounts -> select business account -> profile
3) there would be a popup of Account profile, click on "API Credentials" Tab.
