### ISSUE TITLE
3-0-stable refund view is no longer working due to current_symbol_position is no longer an preference option in spree

### ISSUE THREAD

**Issue by simontseng** [spree-contrib/better_spree_paypal_express#170]
I found 3-0-stable refund view is no longer working due to current_symbol_position is no longer an preference option in spree.

I removed the if statement around it so that it is display just as if it is with option "before" for the current_symbol_position.

Quick investigation, looks like spree is move the options into spree_i18n which is an addon that is not installed by default.

I don't mind to submit a PR but need some pointers showing what's the best way to do it.

**Comment by mleglise** [comment]
+1

**Comment by giupea** [comment]
+1

**Comment by simontseng** [comment]
just tried to submit an PR
#174

**Comment by alepore** [comment]
#174 merged
