### ISSUE TITLE
Support Spree 3.1

### ISSUE THREAD

**Issue by gaqzi** [spree-contrib/better_spree_paypal_express#186]
This library is still very useful because the Braintree/PayPal vZero API is not available outside of the US. As such using better_spree_paypal_express is my best option! :)

I have a branch of it that's passing all the tests for 3.1 support. But I'm a little uncertain on how to get it to mainline since I don't see how to suggest creating a new branch on a PR.

https://github.com/gaqzi/better_spree_paypal_express/tree/3-1-stable

**Comment by justinemar** [comment]
How can i use this?

**Comment by damianlegawiec** [comment]
Workw with Spree 3.1 :)
