### ISSUE TITLE
its support with spree 3.2.0 ?

### ISSUE THREAD

**Issue by suryatresna** [spree-contrib/better_spree_paypal_express#193]
Helo,
i am use spree 3.2.0 with rails 5. when i trying install this repo `gem 'spree_paypal_express', github: 'spree-contrib/better_spree_paypal_express', branch: '3-0-stable'` i get this error.
```
Bundler could not find compatible versions for gem "spree_core":
  In snapshot (Gemfile.lock):
    spree_core (= 3.2.0.rc2)

  In Gemfile:
    spree (~> 3.2.0.rc1) was resolved to 3.2.0.rc2, which depends on
      spree_core (= 3.2.0.rc2)

    spree (~> 3.2.0.rc1) was resolved to 3.2.0.rc2, which depends on
      spree_core (= 3.2.0.rc2)

    spree (~> 3.2.0.rc1) was resolved to 3.2.0.rc2, which depends on
      spree_core (= 3.2.0.rc2)

    spree (~> 3.2.0.rc1) was resolved to 3.2.0.rc2, which depends on
      spree_core (= 3.2.0.rc2)

    spree (~> 3.2.0.rc1) was resolved to 3.2.0.rc2, which depends on
      spree_core (= 3.2.0.rc2)

    spree_gateway (~> 3.2.0.beta) was resolved to 3.2.0.beta, which depends on
      spree_core (< 4.0, >= 3.1.0)

    spree_gateway (~> 3.2.0.beta) was resolved to 3.2.0.beta, which depends on
      spree_core (< 4.0, >= 3.1.0)

    spree_paypal_express was resolved to 2.0.3, which depends on
      spree_core (~> 2.4.0)
```

can it make support with it.

thanks,

**Comment by jomarbarnobal** [comment]
same

**Comment by Shanison** [comment]
The 3-0-stable branch's source code is working fine with Spree 3.2.0 but needs to bump up the dependency request. I have created a new 3-2-stable branch and have sent in a pull request. https://github.com/spree-contrib/better_spree_paypal_express/pull/194 

If you wish to use immediately, you can checkout the code from https://github.com/Shanison/better_spree_paypal_express

**Comment by jomarbarnobal** [comment]
is it working now, and just adding question, i use SSL in my production  and works fine except on admin paymanet method and products i get an error of mixed content

**Comment by justinemar** [comment]
How about 3.3?

**Comment by damianlegawiec** [comment]
@suryatresna @jomarbarnobal @justinemar

`master` branch now works with Spree 3.1, 3.2, 3.3 and 3.4 :)
