### ISSUE TITLE
 1 error prohibited this record from being saved:

### ISSUE THREAD

**Issue by kfn8dkodemonkey** [spree-contrib/better_spree_paypal_express#57]
1 error prohibited this record from being saved:

There were problems with the following fields:

    No payment methods are configured for this environment

Hello,

I am using the spree Paypal express gem for spree commerce.
I am running on ruby 2 rails 3.2.14 and spree 1.3. I have followed the gems readme 
file to a 'T' and I am unable to make paypal work for test or live. 

another not on this is I have also tried to use the cutting edge master for spree and this gem on rails 4 and i am still unable to make it work. 

any help would be great I would like to us paypal.

**Comment by alepore** [comment]
closing old stale issues
