### ISSUE TITLE
The single-table inheritance mechanism failed to locate the subclass: 'Spree::BillingIntegration::PaypalExpress'.

### ISSUE THREAD

**Issue by alexmarles** [spree-contrib/better_spree_paypal_express#8]
Hi everyone,

I'm in the checkout delivery step and when I click on **Save and Continue** I get this error:

**The single-table inheritance mechanism failed to locate the subclass: 'Spree::BillingIntegration::PaypalExpress'. This error is raised because the column 'type' is reserved for storing the class in case of inheritance. Please rename this column if you didn't intend it to be used for storing the inheritance class or overwrite Spree::PaymentMethod.inheritance_column to use another column for that information.**

My Ruby, Rails and Gemfile are:

```
» ruby -v
ruby 1.9.3p327 (2012-11-10 revision 37606) [x86_64-darwin11.4.2]
```

```
» rails -v
Rails 3.2.14
```

```
» cat Gemfile
source 'https://rubygems.org'

gem 'rails', '3.2.14'

gem 'mysql2'
gem 'rmagick'
gem 'friendly_id'

gem 'capistrano'
gem 'capistrano-rbenv'
gem 'unicorn'
gem 'thin'
gem 'slim'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

gem 'spree', git: 'https://github.com/spree/spree.git', branch: '2-0-stable'
gem 'spree_gateway', git: 'https://github.com/spree/spree_gateway.git', branch: '2-0-stable'
gem 'spree_auth_devise', git: 'https://github.com/spree/spree_auth_devise.git', branch: '2-0-stable'
gem 'spree_i18n', git: 'git://github.com/spree/spree_i18n.git', branch: '2-0-stable'

gem 'spree_paypal_express', :github => "radar/better_spree_paypal_express", :branch => "2-0-stable"
gem "spree_sermepa", git: 'git://github.com/picazoH/spree_sermepa.git'

group :development do
  gem 'better_errors'
  gem 'meta_request'
  gem 'quiet_assets'
end
```

**Comment by drewmoore** [comment]
I tried destroying the payment method in the console, but received the exact same error that was thrown before.  ActiveRecord can't find the payment method subclass, much less delete it. Maybe I'm missing something, still kind of a nube...

**Comment by SamBelmor** [comment]
You should delete it by the admin side, that worked for me.
