### ISSUE TITLE
auto_capture? always true 

### ISSUE THREAD

**Issue by jhirbour** [spree-contrib/better_spree_paypal_express#84]
I'm using Rails 4.02 with Spree 2-1-stable and trying to setup Spree to only authorize and not capture. This is the behavior of our current PHP app that we are trying to replicate w/ Spree.

After talking with @GeekOnCoffee on IRC referred me to  http://guides.spreecommerce.com/developer/payments.html . I've set "config.auto_capture=false" in my spree initializer to authorize and not capture payments as per the doc.

I've done this in our spree initializer, but spree_paypal_express seems to ignore this value and always performs a purchase.  

Is this a bug? or does the gem not support authorize only ?

```
Spree.config do |config|
  config.auto_capture=false
end
```

```
gem 'rails', '~> 4.0.2'

# spree stuff
gem 'spree', git: 'https://github.com/spree/spree.git', :branch => '2-1-stable'
gem 'spree_paypal_express', :git => 'https://github.com/radar/better_spree_paypal_express.git', :branch => '2-1-stable'
gem 'spree_gateway', :git => 'https://github.com/spree/spree_gateway.git', :branch => '2-1-stable'
gem 'spree_volume_pricing', :git => 'https://github.com/spree/spree_volume_pricing.git', :branch => '2-1-stable'
gem 'spree_sitemap', git: 'https://github.com/jdutil/spree_sitemap.git'
```

**Comment by alepore** [comment]
closing old stale issues
